name: .NET Unit Test

on:
  push:
    branches: [ tu2 ]
  pull_request:
    branches: [ tu2 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore History.sln

    - name: Build
      run: dotnet build History.sln --no-restore

    - name: Run Tests
      run: dotnet test History.sln --no-build --verbosity normal
